### ISSUE TITLE
Recurring reservations page crashes if no workplaces are defined

### ISSUE THREAD

**Issue by florian-glombik** [florian-glombik/workplace-reservation#60]
**Describe the bug**
Page crashes

**To Reproduce**
1. Have no workspaces
2. Navigate to `Recurring Reservations`
3. See that the page crashes

**Expected behavior**
Page should not crash

**Screenshots**

**Additional context**
```
ReoccuringReservationsForm.tsx:145 TypeError: Cannot read properties of null (reading 'map')
    at Hh (ReoccuringReservationsForm.tsx:259:23)
    at ii (react-dom.production.min.js:157:137)
    at Hi (react-dom.production.min.js:180:154)
    at Gs (react-dom.production.min.js:269:343)
    at Pl (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Tl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

issue with 
```
 {workplaces.map((workplace) => (
            <MenuItem value={workplace.ID} key={workplace.ID}>
              {getWorkplaceName(workplace)}
            </MenuItem>
          ))}
```

**Comment by florian-glombik** [comment]
Fixed in https://github.com/florian-glombik/workplace-reservation/pull/68
